# Generated by Django 4.2.7 on 2023-11-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=255, verbose_name='ФИО отправителя')),
                ('recipient_name', models.CharField(max_length=255)),
                ('sending_location', models.CharField(max_length=255)),
                ('receiving_location', models.CharField(max_length=255)),
                ('sending_index', models.CharField(max_length=10)),
                ('receiving_index', models.CharField(max_length=10)),
                ('letter_type', models.CharField(choices=[('Letter', 'Letter'), ('Registered Letter', 'Registered Letter'), ('Valuable Letter', 'Valuable Letter'), ('Express Letter', 'Express Letter')], max_length=20)),
                ('letter_weight', models.FloatField()),
            ],
            options={
                'verbose_name': 'Письмо',
                'verbose_name_plural': 'Письма',
            },
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=255)),
                ('recipient_name', models.CharField(max_length=255)),
                ('sending_location', models.CharField(max_length=255)),
                ('receiving_location', models.CharField(max_length=255)),
                ('sending_index', models.CharField(max_length=10)),
                ('receiving_index', models.CharField(max_length=10)),
                ('notification_phone', models.CharField(max_length=20)),
                ('parcel_type', models.CharField(choices=[('Small Parcel', 'Small Parcel'), ('Parcel', 'Parcel'), ('First-Class Parcel', 'First-Class Parcel'), ('Valuable Parcel', 'Valuable Parcel'), ('International Parcel', 'International Parcel'), ('Express Parcel', 'Express Parcel')], max_length=30)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Посылка',
                'verbose_name_plural': 'Посылки',
            },
        ),
    ]
