# Generated by Django 4.2.7 on 2023-11-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='letter_type',
            field=models.CharField(choices=[('Letter', 'Письмо'), ('Registered Letter', 'Заказное письмо'), ('Valuable Letter', 'Ценное письмо'), ('Express Letter', 'Экспресс письмо')], max_length=20, verbose_name='Тип письма'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='letter_weight',
            field=models.FloatField(verbose_name='Вес письма'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='receiving_index',
            field=models.CharField(max_length=10, verbose_name='Индекс места получения'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='receiving_location',
            field=models.CharField(max_length=255, verbose_name='Пункт получения'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='recipient_name',
            field=models.CharField(max_length=255, verbose_name='ФИО получателя'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='sending_index',
            field=models.CharField(max_length=10, verbose_name='Индекс места отправки'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='sending_location',
            field=models.CharField(max_length=255, verbose_name='Пункт отправки'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='notification_phone',
            field=models.CharField(max_length=20, verbose_name='Телефон для извещения'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='parcel_type',
            field=models.CharField(choices=[('Small Parcel', 'Мелкий пакет'), ('Parcel', 'Посылка'), ('First-Class Parcel', 'Посылка первого класса'), ('Valuable Parcel', 'Ценная посылка'), ('International Parcel', 'МЕждународная посылка'), ('Express Parcel', 'Экспресс посылка')], max_length=30, verbose_name='Тип посылки'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма платежа'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='receiving_index',
            field=models.CharField(max_length=10, verbose_name='Индекс места получения'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='receiving_location',
            field=models.CharField(max_length=255, verbose_name='Пункт получения'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='recipient_name',
            field=models.CharField(max_length=255, verbose_name='ФИО получателя'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='sender_name',
            field=models.CharField(max_length=255, verbose_name='ФИО отправителя'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='sending_index',
            field=models.CharField(max_length=10, verbose_name='Индекс места отправки'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='sending_location',
            field=models.CharField(max_length=255, verbose_name='Пункт отправки'),
        ),
    ]
